### ISSUE TITLE
Legacy asks not saving on Chrome

### ISSUE THREAD

**Issue by Felina-Lain** [AprilSylph/Outbox-for-Tumblr#10]
### Platform

Win10

### Browser

Chrome 96.0.4664.45

### Addon version

Beta 0.5.2

### Details

Hello
The extension (installed from chrome store) doesn't appear to work at all. I sent an ask, just yesterday, to a friend (with a name.tumblr.com/ask link) and the ask did not appear in my outbox in the extension page
Is there a step I might have missed, to connect the extension to my tumblr maybe?

thanks in advance!

**Comment by AprilSylph** [comment]
Appears that this is specific to /ask pages on Chrome. I've probably unknowingly used a Firefox-specific attribute in writing the legacy ask saver. Asks sent from the dashboard still save correctly for me.

**Comment by AprilSylph** [comment]
This is fixed in Beta 0.5.3, which was just now approved by the Chrome Web Store. You can receive the update immediately by navigating to `chrome://extensions`, enabling developer mode, then clicking the "Update" button.

Thanks for bringing this to my attention!
