### ISSUE TITLE
Raw historical outbox data json file not accepted by extension

### ISSUE THREAD

**Issue by jellygem** [AprilSylph/Outbox-for-Tumblr#18]
I downloaded the raw jason file from the old xkit outbox extension and uploaded it to the new chrome extension page but I get this error message every time. If it means anything, the json file has an icon preview of the firefox symbol in my chrome download bar.

<img width="1160" alt="Screen Shot 2022-01-20 at 3 44 32 PM" src="https://user-images.githubusercontent.com/73639829/150419304-ba86f799-680f-4158-ae7d-4e1b35f98556.png">

**Comment by marcustyphoon** [comment]
This isn't currently a supported feature! I guess I didn't manage to make the wording around old XKit's export button clear enough, sorry.
