### ISSUE TITLE
error with anon asks

### ISSUE THREAD

**Issue by starling0526** [AprilSylph/Outbox-for-Tumblr#94]
### Platform

macOS Sonoma 14.5

### Browser

Orion Version 0.99.127.3-beta (WebKit 619.1.1)

### Addon version

0.23.6

### Details

while trying to test on my computer i seemed to be getting an error reading

_Something went wrong._

followed by

_TypeError: undefined is not an object (evaluating 'array.reduce')_

<img width="1107" alt="Screenshot 2024-06-22 at 20 36 14" src="https://github.com/AprilSylph/Outbox-for-Tumblr/assets/123284443/2387330f-d837-4522-883e-79c1ff897005">

the ask was through the blog's `https://www.tumblr.com/blogname` page rather than a `blogname.tumblr.com`page

not sure if could have possibly been an issue with my browser, but i assumed it would run okay since orion supports chrome web store and the xkit extension itself seems to be working fine for me? 😭

**Comment by marcustyphoon** [comment]
Hmm, do you get the same result in Chrome/Firefox? In my experience, Orion's simulation of the extension APIs is somewhat incomplete (and they haven't been quick to address the one I bug reported, which is totally fair but means I don't think the browser becoming a support target is super likely). I'm not against implementing fixes, but I would have to know what to look for!

**Comment by starling0526** [comment]
okay so i tried and i _was_ able to get it to work in chrome, but yeah i'm still not getting anything through orion rn; just the same error message i attached originally :/

**Comment by marcustyphoon** [comment]
Did some quick tests. This is unrelated to the anon ask or having sent anything at all; the options page is just broken in Orion. Why?

https://github.com/AprilSylph/Outbox-for-Tumblr/blob/8db9603052af1be0d6d3596ef695507c794f01a4/src/lib/npf.js#L10

https://github.com/AprilSylph/Outbox-for-Tumblr/blob/8db9603052af1be0d6d3596ef695507c794f01a4/src/outbox.js#L162-L164

For whatever reason, Orion makes the property that nightpool's code adds to the Object prototype enumerable in this particular case, so it appears as an entry in `Object.entries`.

On the one hand, modifying the prototype chain is pretty unusual and generally regarded as bad practice as far as I know, so I see why this might not have shown up in Kagi's testing. On the other, this absolutely should work, and the way that it doesn't implies extremely bad things to me about whatever Orion is doing to the javascript engine.

**Comment by starling0526** [comment]
interesting.....

for context, i'd only recently switched to orion very recently as i'm primarily a safari user but i've used xkit a handful of times before a few years ago to clean up old blogs. i usually try not to mess with codes or scripts or really anything other than tumblr custom theme codes, so i'd given up trying to convert any google extensions by myself and instead was trying to find browser that would be more customizable while still allowing me to use certain extensions (since i typically opera downloaded solely for when i need my extensions).

i'd heard about them while going through a couple tech youtubers' pages and reddit comment threads, and the video i saw in particular said that some extensions were somewhat expected not to work at full capacity or that the browser itself may be a bit buggy??? or at least something along such lines, as i don't remember the video right now.

i'll keep note of this though, since modifying the prototype chain does sound a little odd to me. in the meantime i would suppose this means there's may not really be a way around this for now/it would be better recommended for me to just continue using the extension in another browser if i really wanted to use it?

**Comment by marcustyphoon** [comment]
That sounds like an accurate characterization to me. It's a little bit of an odd scenario now in that Safari has its own code to support web extensions built into it now—but Apple only allows them to be installed if they're packaged in a Mac app, which is a bit of a pain. Based on my experiences with both browsers and just the relative amount of development resources they have available, it doesn't surprise me that Orion breaks in this instance, but it would surprise me of Safari did.

Obviously if Orion can eventually just use Safari's code that implements the extension APIs, modifying only the method to load extensions at all, that would be ideal. Well—okay, what would actually be ideal is Safari just not having the Mac app requirement, but who knows if Apple wants to do that.

**Comment by starling0526** [comment]
yeah that's understandable, though i doubt apple will budge any time soon.

like i said before, i gave up pretty quick after i had tried following a tutorial a little while back that was for converting google extensions, that way i could at least _attempt_ to have them in safari. it was a bit of a pain and i didn't have the brain juice for it at the time (which, at the moment especially sucks due to the mac app requirement since i heard the subscription needed to make an extension publicly available on a large scale is still like $100 a year 😭).

i suppose for now i'll be sticking to using xkit & outbox on opera and will have to just try and be more mindful of when i'm sending out my anon asks. thank you for looking into this though! i appreciate the help.
